spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: info
    org.greyhawk: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.springframework.data.mongodb.repository.query: debug
